{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatbot-webapp.keycloakName" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "chatbot-webapp.keycloakLabels" . | nindent 4 }}
type: Opaque
stringData:
  admin-username: {{ .Values.keycloak.admin.username | quote }}
  admin-password: {{ include "chatbot-webapp.keycloakAdminPassword" . | quote }}
  {{- if and .Values.keycloak.database.enabled (not .Values.keycloak.database.existingSecret) }}
  db-password: {{ randAlphaNum 16 | quote }}
  {{- end }}
{{- end }}
