{{- if .Values.webapp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatbot-webapp.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "chatbot-webapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.webapp.autoscaling.enabled }}
  replicas: {{ .Values.webapp.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chatbot-webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.webapp.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "chatbot-webapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.webapp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chatbot-webapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.webapp.podSecurityContext | nindent 8 }}
      containers:
      - name: webapp
        securityContext:
          {{- toYaml .Values.webapp.securityContext | nindent 10 }}
        image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.webapp.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.webapp.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.webapp.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
      volumes:
      - name: config
        configMap:
          name: {{ include "chatbot-webapp.fullname" . }}
      {{- with .Values.webapp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webapp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webapp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
