{{- if and .Values.webapp.enabled .Values.webapp.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chatbot-webapp.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "chatbot-webapp.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chatbot-webapp.fullname" . }}
  minReplicas: {{ .Values.webapp.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.webapp.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.webapp.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.webapp.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.webapp.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.webapp.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
