{{- if .Values.oauth2Proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot-webapp.oauth2ProxyName" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "chatbot-webapp.oauth2ProxyLabels" . | nindent 4 }}
  {{- with .Values.oauth2Proxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.oauth2Proxy.service.type }}
  ports:
  - port: {{ .Values.oauth2Proxy.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "chatbot-webapp.oauth2ProxySelectorLabels" . | nindent 4 }}
{{- end }}
